[SHIP-5023] API Cargowise reference Endpoint description
softdev15/slate pull request #39
Opened 2021-07-21 11:46 UTC by SowmyaLakkegowda29

2021-07-21 11:58 UTC, lphkaldn commented on source/index.html.md
> +```
Do we get syntax highlighting with ``` xml?

2021-07-21 11:58 UTC, lphkaldn commented on source/index.html.md
> +```
see above

2021-07-21 11:58 UTC, lphkaldn commented on source/index.html.md
> +```
see above

2021-07-21 11:58 UTC, lphkaldn commented on source/index.html.md
> +```
see above

2021-07-21 11:58 UTC, lphkaldn commented on source/index.html.md
> +```
see above

2021-07-21 14:10 UTC, SowmyaLakkegowda29 commented on source/index.html.md
> +```
Ah good spot!

2021-07-21 15:27 UTC, lphkaldn requested changes
I'm not sure why, but this still does not highlight the xml. Please check the characters ```xml and the do a visual check locally if the elementes are coloured.

2021-07-22 09:03 UTC, lphkaldn approved these changes

2021-07-23 07:19 UTC, merged